program: code/algorithm/main.py
method: grid
project: "class-conditional-label-noise"
name: "Estimated transition sweep CIFAR Backward"
description: "Grid search over CIFAR dataset backward loss correction."
parameters:
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  loss_correction:
    value: "backward"
  dataset:
    value: "cifar"
  lr:
    value: 0.0001
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--wandb"
  - "--estimator"
  - "anchor"
  - "--epochs"
  - 128
  - ${args}
